### ISSUE TITLE
How to add my custom imag emojis

### ISSUE THREAD

**Issue by ape660** [walsvid/logseq-emoji-picker-fork#2]

**Comment by candideu** [comment]
The API used has this in their docs: https://picmojs.com/docs/usage/custom/

Not sure how to make this work on this app, though...

**Comment by walsvid** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/17134911/227127891-79d88ab6-8f2e-4a2c-b105-a9ed55fc2a53.png">

In fact I have added custom emoji in the last panel. However, it is currently not implemented for users to add custom emoji locally. Contributions are welcome! 

Another issue is that custom emoji can only be inserted in the form of pictures in logseq, and the current UI has some bugs in handling the mixed arrangement of text and pictures, and in some cases the desired effect cannot be obtained. Please see https://github.com/logseq/logseq/issues/6070 for details.

**Comment by candideu** [comment]
@walsvid Makes sense, thanks for pointing out the custom emoji you've already added and the current bugs.

I not at all familiar with Logseq plugin development, but my hunch would be to make the custom emojis configurable in the plugin settings (via `logseq.App.getUserConfigs` or something).

So [lines 19-48 in index.ts](https://github.com/walsvid/logseq-emoji-picker-fork/blob/main/index.ts#L19-L48) could be modifiable in the plugin settings JSON, and users would just have to add as many entries as they want for their custom emojis.

![image](https://user-images.githubusercontent.com/55474996/227565582-1d7a2692-d0cf-4cab-b48c-08bdd5c09116.png)

[logseq-plugin-wrap](https://github.com/sethyuan/logseq-plugin-wrap/blob/master/src/index.jsx) does this to allow users to modify and add more options to the toolbar.

**Comment by walsvid** [comment]
Hi all, I have update the plugin to [v0.0.3.](https://github.com/walsvid/logseq-emoji-picker-fork/tree/v0.0.3) The new version supports adding custom emojis via json config file. After updating the configuration, please restart logseq or toggle the plugin to make the custom emoji settings take effect. 

Feel free to reopen the issue again.

**Comment by candideu** [comment]
Amazing, thank you @walsvid ! I've filmed a demo, and I'll make a PR to add to the README.

**Comment by candideu** [comment]
@walsvid Another limitation I've noticed is that custom emojis which are saved in the assets folder aren't previewed, although they appear when you add them to the page.

![image](https://user-images.githubusercontent.com/55474996/227786744-86b8cc96-9691-42c0-895d-63c94f4687ed.png)

**Comment by walsvid** [comment]
Hi, @candideu. The picmo library used by this plugin manages and renders custom emoji/image by url, so there will be rendering problems when using local files. My suggestion is to use an image hosting service to convert local images to accessible urls.
