### ISSUE TITLE
Changing emoji renderers?

### ISSUE THREAD

**Issue by joaosimuai** [walsvid/logseq-emoji-picker-fork#5]
Is it possible to change the renderer from native to Twemoji as in picmo's Doc? Been trying to make the country flags visible as they're not natively in Windows.

**Comment by walsvid** [comment]
In order to match the system natively and consider users of other systems, I can only using native emoji in the logseq plugin. The Twemoji solution as you mentioned may only be considered if the plugin can released separately by windows. 

Contributions are always welcome!
