### ISSUE TITLE
Feature request: First page set to RECENTLY USED

### ISSUE THREAD

**Issue by Endle** [walsvid/logseq-emoji-picker-fork#6]
With my personal experience, 99% of my emoji usage are centred on about 10 high frequency emojis. Clicking from the recently used list is much faster than typing and searching for the 99% cases.

Could it possible to set the first page at recently used, or make it an option?

Thank you.

**Comment by walsvid** [comment]
Good question, I need to think about how to implement this.

**Comment by walsvid** [comment]
Hi @Endle , the default category is set to recently used in v0.0.5: https://github.com/walsvid/logseq-emoji-picker-fork/commit/5778768727a1a117aaf34d9c7ba9f3a985ae6827
