### ISSUE TITLE
Party parrot emoji not available anymore

### ISSUE THREAD

**Issue by mainrs** [walsvid/logseq-emoji-picker-fork#7]
The imgur link is dead:
https://github.com/walsvid/logseq-emoji-picker-fork/blob/5778768727a1a117aaf34d9c7ba9f3a985ae6827/index.ts#L35-L40

**Comment by walsvid** [comment]
I'll update soon. During this time, party parrot can be used by customizing emoji

**Comment by walsvid** [comment]
It has been updated, please use version 0.0.6. Close the issue now, if there is a problem, please feel free to re-open the issue.
